# coding=utf-8
"""Module holding all currently useable Materials as well utilities for them """
from enum import Enum, auto


class Material (Enum):
    """ Represents a Material -
    Materials should be compared by entity, not by value"""
    
    # More values should be generated by a script (will add later)
    # it would take a long time to do this all by hand
    # as such, this Set of enums is bound to change
    AIR = auto()
    BEDROCK = auto()
    BIRCH_LEAVES = auto()
    BIRCH_LOG = auto()
    BIRCH_PLANKS = auto()
    CAVE_AIR = auto()
    COAL_ORE = auto()
    DIAMOND_ORE = auto()
    DIRT = auto()
    EMERALD_ORE = auto()
    GOLD_ORE = auto()
    GRASS = auto()
    GRASS_BLOCK = auto()
    IRON_ORE = auto()
    LAPIS_ORE = auto()
    OAK_LEAVES = auto()
    OAK_LOG = auto()
    OAK_PLANKS = auto()
    REDSTONE_ORE = auto()
    SPRUCE_LEAVES = auto()
    SPRUCE_LOG = auto()
    SPRUCE_PLANKS = auto()
    STONE = auto()
    VOID_AIR = auto()
    
    # ----------- UTILITY METHODS BELOW ----------
    def is_air(self):
        return  bool(self is Material.AIR or self is Material.CAVE_AIR or self is Material.VOID_AIR)
    
